### ISSUE TITLE
On uninstallation, there is an error because "LICENSE.txt" doesn't exist that prevents it from completing

### ISSUE THREAD

**Issue by vaartis** [wakatime/visualstudio-wakatime#105]
When uninstalling the plugin, I got an error message that said the file `C:\Users\MYUSER\AppData\Local\Microsoft\VisualStudio\16.0_1d542bea\Extensions\LICENSE.txt` doesn't exist which prevents the plugin from uninstalling. Manually creating that file allowed me to uninstall it successfully.

**Comment by gandarez** [comment]
That file is not related to `WakaTime` installation. All files needed to uninstall WakaTime is in a folder further. Because Visual Studio creates a hash to identify the folder you might see them with different hashes and after you find it you realize that the file `LICENSE.txt` exists.

Visual Studio Extensions folder in my machine: `C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\16.0_22f4b855\Extensions`
![image](https://user-images.githubusercontent.com/782854/89641969-3b959780-d889-11ea-805c-3fad0def03d4.png)

Folder content for `WakaTime`
![image](https://user-images.githubusercontent.com/782854/89641912-20c32300-d889-11ea-91f4-8d0d7f5a5b11.png)

**Comment by alanhamlett** [comment]
Re-opening because another report came in showing the error is still occurring when trying to uninstall.

![visualstudio-uninstall-error](https://user-images.githubusercontent.com/522344/106182474-b3b38a80-6153-11eb-8a14-8b12821bf945.png)

**Comment by pluczak99** [comment]
I encountered this problem on Jan 28th 2021 with the version of WakaTime that was most recent at the time and was installed as an extension in VS.NET 2019 Enterprise. 

Creating an empty LICENSE.TXT file in the path mentioned by @alanhamlett (modified accordingly for my user name) resolves the problem.

BTW I would suggest that if WakaTime uses folder EXTENSIONS as the location to place the license file, it should create its own subfolder like many other VS.NET extensions and store LICENSE.TXT in there. Otherwise there may be conflicts if another VS.NET extension, utilizing the EXTENSIONS folder to store its own license file (possibly using the same LICENSE.TXT file naming scheme).

**Comment by peeush-the-developer** [comment]
+1 @pluczak99 
I encountered the same issue today with uninstall of WakaTime extension from VS 2019. I had to add an empty "LICENSE.TXT" file in my VS 2019 Extensions folder to successfully uninstall the same.

**Comment by mingy532** [comment]
I encountered the same issue,thanks for @peeush-the-developer

**Comment by gandarez** [comment]
We've just released a new version (` v11.0.0`) that fixes this issue.
