### ISSUE TITLE
Wakatime does not recognize .Razor files and places them in other

### ISSUE THREAD

**Issue by tiberhealth** [wakatime/visualstudio-wakatime#114]
It looks like Wakatime marks .razor files (Blazor source) as other.  We cannot find a way to add the .razor extension as a know file type for analytics purposes. 

To reproduce - open visual studio 2019 and start a Blazor project and start working in one of the .razor files. The analytics is being lumped into the other category. Then work on a .razor.cs file, it looks like the .cs is properly picked up. 

Thanks,
Bryan M Lenihan

**Comment by travisterrell** [comment]
While IMHO this should really be added so that it is categorized automatically, you should be able to set a filter to do it for you.

On the website, go to Settings->Custom Rules, then add a filter for **File _Ends With_** (or **_Contains_**) .razor.

I think this should work.
![image](https://user-images.githubusercontent.com/14238582/211443016-c0546256-aef7-49bb-b93b-81b63fd5f177.png)


As an aside, I discovered this while tracking down why I have a ton of generated DLLs showing up with associated time in  _Other_. Considered adding a filter, but still can't decide whether they represent time I was actively coding or not, since they're binaries, ha. (I actually came here to leave an issue about it, but seeing yours unaddressed for the better part of a year makes me think it may not be worth my time, ha.)

**Comment by alanhamlett** [comment]
I've added support for `.razor` files to the backend, based on file extension. Normally the language detection lives in our [Chroma](https://github.com/wakatime/chroma/tree/master/lexers/r) repo.

**Comment by alanhamlett** [comment]
Related https://github.com/wakatime/chroma/pull/123.
