### ISSUE TITLE
Every VS Solution I open requires me to install python 

### ISSUE THREAD

**Issue by UnreachableCode** [wakatime/visualstudio-wakatime#3]
I'm not positive this is an issue but my understanding is that I'm meant to install python once in the root directory of windows and then Wakatime should just work without any extra setup but as it stands it keeps requiring me to have python installed in the same place. Did I mess something up with the install?

**Comment by alanhamlett** [comment]
Where is python installed on your machine currently? The plugin looks for python in C:\pythonXX where XX is your version of python. If it doesn't find python there, or in your PATH, then the plugin downloads and installs python.

Since it's doing that multiple times, can you find where the plugin is installing python?

**Comment by UnreachableCode** [comment]
Well I've now worked out that each of these 'installs' as I was previously
referring to has 'Update' in the dialog box that appears. Still finding it
a bit weird that it needs to update for every VS Solution I open though.

The path that it installs the updates to is
here: C:\Users\myusername\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\fl5x5525.n5b

And I definitely have python installed here: C:\Python34.

Is this frequency of updates normal?

Thank you.

**Comment by AlbertoMonteiro** [comment]
Why does wakatime depends on python?

**Comment by alanhamlett** [comment]
@AlbertoMonteiro wakatime depends on python because the [core](https://github.com/wakatime/wakatime) is written in python.

@UnreachableCode that could be from the v0.0.1 of visualstudio-wakatime which installed Python to the VS extension directory which changes every time the plugin updates, breaking the python installation. You can try changing the default install path in your Windows Registry setting using these instructions:
http://www.wincert.net/tips/microsoft-windows/windows-7/1830-how-to-change-default-installation-path-on-windows-7

**Comment by alanhamlett** [comment]
I've gone through the whole plugin code to fix hopefully this and other bugs.
